services:
  minio-rabbitmq-bridge:
    build: .
    ports:
      - "5000:5000"
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - RABBITMQ_QUEUE=minio_events
    networks:
      - portainer_default

networks:
  portainer_default:
    external: true
